# Generated by Django 3.1.5 on 2021-01-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210106_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ttsaudio',
            old_name='name',
            new_name='uri',
        ),
        migrations.AddField(
            model_name='ttsaudio',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ttsaudio',
            name='audio',
            field=models.CharField(max_length=40),
        ),
    ]
