# Generated by Django 3.1.5 on 2021-01-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210119_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttsaudio',
            name='sample_fmt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ttsaudio',
            name='sample_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ttsaudio',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ttsaudio',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
