# Generated by Django 3.1.5 on 2021-01-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210122_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttsaudio',
            name='channel_layout',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ttsaudio',
            name='duration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ttsaudio',
            name='sample_fmt',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ttsaudio',
            name='sample_rate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ttsaudio',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ttsaudio',
            name='uri',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
